services:
  api:
    build:
      context: ./api
    container_name: astro-kovesh-api
    env_file:
      - ./api/.env
    environment:
      APP_ENV: production
    restart: unless-stopped
    ports:
      - "8010:8010"

  web:
    build:
      context: ./web
    container_name: astro-kovesh-web
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - api
